default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zoo_app_development

test:
  <<: *default
  database: zoo_app_test

production:
  <<: *default
  database: zoo_app_production
  pool: 20
